/**
 * Builds the census list from public sources. Re-runnable, deterministic.
 *
 *   pnpm list:build
 *
 * WHY IT IS GENERATED. The census needs a population that a reader can check.
 * A list I typed out by hand is a claim about the world with no source behind
 * it, and at a thousand entries nobody can audit it. These two lists are
 * public, curated by other people, and each entry keeps the section heading
 * its own list filed it under — so every row here can be traced to a line in
 * somebody else's repository.
 *
 * The 51 hand-picked indie products stay as their own group. They are the
 * comparison the open-source group is interesting against.
 */
import { writeFile } from "node:fs/promises";
import { INDIE } from "../src/data/indie";

const SOURCES = [
  {
    id: "awesome-selfhosted",
    url: "https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/README.md",
    repo: "https://github.com/awesome-selfhosted/awesome-selfhosted",
  },
  {
    id: "awesome-sysadmin",
    url: "https://raw.githubusercontent.com/awesome-foss/awesome-sysadmin/master/README.md",
    repo: "https://github.com/awesome-foss/awesome-sysadmin",
  },
] as const;

/* Entries that point at a code host are dropped. 306 of the 1,255 in
   awesome-selfhosted do, and fingerprinting github.com two hundred times would
   report that GitHub runs Ruby, two hundred times. */
const CODE_HOSTS = new Set([
  "github.com", "github.io", "gitlab.com", "gitlab.io", "codeberg.org",
  "sourceforge.net", "readthedocs.io", "readthedocs.org", "bitbucket.org",
  "launchpad.net", "pypi.org", "npmjs.com", "hub.docker.com", "sr.ht",
  "apps.apple.com", "play.google.com", "addons.mozilla.org", "git.sr.ht",
]);

const host = (u: string) => {
  const h = new URL(u).host.toLowerCase();
  return h.startsWith("www.") ? h.slice(4) : h;
};
const registrable = (h: string) => h.split(".").slice(-2).join(".");

type Row = { domain: string; name: string; kind: "indie" | "oss"; src: string; topic: string };

/** Counted while building, and written into the generated file. The method page
 *  used to state this figure from memory: it said 306 dropped, which was true
 *  of one list and wrong from the moment the second was added. A published
 *  number has to be computed by the thing that produces it. */
const stats = { entries: 0, dropped: 0 };

async function fromList(src: (typeof SOURCES)[number]): Promise<Row[]> {
  const md = await (await fetch(src.url, { headers: { "user-agent": "stackcensus.onedaybuilt.com" } })).text();
  const rows: Row[] = [];
  let topic = "Uncategorised";
  for (const line of md.split("\n")) {
    /* The section heading the list itself filed the entry under. Free, honest
       categories: they are the maintainers' judgement, not mine. */
    const h = /^#{2,3}\s+(.+?)\s*$/.exec(line);
    if (h) topic = h[1].replace(/\[|\]|\(.*\)/g, "").trim();
    const m = /^- \[([^\]]+)\]\((https?:\/\/[^)]+)\)/.exec(line);
    if (!m) continue;
    stats.entries++;
    let h2: string;
    try {
      h2 = host(m[2]);
    } catch {
      stats.dropped++;
      continue;
    }
    if (CODE_HOSTS.has(h2) || CODE_HOSTS.has(registrable(h2))) {
      stats.dropped++;
      continue;
    }
    rows.push({ domain: h2, name: m[1].trim(), kind: "oss", src: src.id, topic });
  }
  return rows;
}

const seen = new Map<string, Row>();
for (const s of INDIE) seen.set(s.domain, { ...s, kind: "indie", src: "hand-picked" });
let fromLists = 0;
for (const src of SOURCES) {
  const rows = await fromList(src);
  fromLists += rows.length;
  /* First list wins a duplicate domain, and the hand-picked 51 win over both:
     a product that is in two lists is one product, and it must be counted once
     or every figure on the site is wrong. */
  for (const r of rows) if (!seen.has(r.domain)) seen.set(r.domain, r);
}

const all = [...seen.values()].sort((a, b) => a.domain.localeCompare(b.domain));
const counts = { indie: all.filter((r) => r.kind === "indie").length, oss: all.filter((r) => r.kind === "oss").length };

const body = `/* GENERATED by scripts/build-list.mts — do not edit by hand.
 *
 * ${all.length} products: ${counts.indie} hand-picked indie products and ${counts.oss}
 * open-source tools from two public lists. Sources, so that any row can be
 * traced back:
${SOURCES.map((s) => ` *   ${s.id}: ${s.repo}`).join("\n")}
 *
 * \`topic\` is the section heading the source list filed the entry under. For
 * the hand-picked 51 it is the category of what the product does.
 *
 * Regenerate with: pnpm list:build
 */
import type { CensusSite } from "@/data/indie";

export const SITES: CensusSite[] = ${JSON.stringify(all, null, 1)};

export const byDomain = new Map(SITES.map((s) => [s.domain, s]));

/** What the two public lists contained, and what was thrown away. Printed on
 *  /method, so it is computed here rather than remembered. */
export const LIST_STATS = { entries: ${stats.entries}, droppedCodeHosts: ${stats.dropped} };
`;

await writeFile("src/data/sites.ts", body);
console.log(`${all.length} products written to src/data/sites.ts`);
console.log(`  hand-picked indie: ${counts.indie}`);
console.log(`  open source:       ${counts.oss}  (from ${fromLists} list entries, duplicates and code hosts removed)`);
